hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("xremap ~/.config/xremap/config.yml")
    hl.exec_cmd("hyprctl setcursor catppucin-mocha-dark-cursors 24")
end)
