require("hyprland.colors")
require("hyprland.monitors")
require("hyprland.keybinds")
require("hyprland.autostart")
require("hyprland.env")
require("hyprland.appearance")
require("hyprland.input")
require("hyprland.rules")